/*
 * coqui_runtime.h --- cuAFL device-side runtime contract.
 *
 * Shared header between the LLVM pass plugin and the GPU runtime .c files.
 * Declares types, constants, and function prototypes used across passes.
 *
 * Compile with: --target=nvptx64-nvidia-cuda -O2 -ffreestanding
 */

#ifndef _COQUI_RUNTIME_H
#define _COQUI_RUNTIME_H

#include <stdint.h>

/* Basic types (matching AFL's u8/u32/u64 convention) */
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

/* -- Constants --
 *
 * Coverage map is per-edge (SanitizerCoverage trace-pc-guard): size is
 * determined at link time by the SancovCount pass and exposed to the host
 * via @__coqui_num_edges. The runtime reads the size via
 * __coqui_cov_map_size() (pass-materialized constant). No 64 KB AFL default. */

/* Phase markers (written to coqui_status_t.phase by kernel logic) */
#define COQUI_PHASE_EMPTY       0
#define COQUI_PHASE_START       1
#define COQUI_PHASE_EXECUTING   2
#define COQUI_PHASE_EXITED      3
#define COQUI_PHASE_BUCKETING   4
#define COQUI_PHASE_VIRGIN_CMP  5
#define COQUI_PHASE_COMPLETE    6
#define COQUI_PHASE_RESERVED    7

/* Per-thread status reported to the host.
 *
 * Layout is BYTE-IDENTICAL to the host-side coqui_status_t in
 * include/afl-fuzz-coqui.h (same field order, same sizeof=16). The kernel
 * writes via its 16-byte stride; cuMemAlloc on the host uses the host
 * sizeof, so the two MUST agree or writes alias across slots. */
typedef struct coqui_status {
    u8  phase;
    u8  signal;        /* POSIX signal number or 0 */
    u8  asan_error;    /* non-zero if ASan check tripped */
    u8  ubsan_fatal;   /* non-zero if non-recoverable UBSan (future) */
    u32 crash_sig;     /* FNV-1a hash of classified cov_map; 0 if not crashed */
    u64 _reserved1;
} coqui_status_t;       /* 16 bytes */

/* -- Device-side helpers (implemented in runtime .c files) -- */

/* Thread identity */
u32 __coqui_fuzz_tid(void);

/* Trap / exit */
void __coqui_trap(void);   /* PTX `trap;` — unrecoverable */
void __coqui_exit(void);   /* PTX `exit;` — this thread exits, kernel continues */

/* Status writing */
void __coqui_status_set_phase(u32 tid, u8 phase);

/* Region accessors (set up by MemoryLayout transform at kernel entry) */
u8  *__coqui_cov_base(void);       /* per-thread coverage map slot (size given by __coqui_cov_map_size) */
u8  *__coqui_heap_base(void);      /* per-thread heap */
u8  *__coqui_shadow_base(void);    /* per-thread ASan shadow */
u32  __coqui_heap_size(void);      /* runtime-configured heap size */
u64  __coqui_cov_map_size(void);   /* per-thread cov_map size in bytes (=num_edges rounded to 4) */

/* -- Coverage runtime --
 *
 * __coqui_coverage_evaluate: classify the per-thread counter map, zero it in
 * place, atom.or-merge the warp's classified result into the global bitmap.
 * Returns 1 if this thread contributed novelty, 0 otherwise.
 *
 * cov_map_size MUST be a multiple of 4 (rounded up from num_edges).
 */
int __coqui_coverage_evaluate(u8 *thread_cov, u8 *global_cov, u64 cov_map_size);

/* Dedup hash of the (current contents of the) cov_map at crash time. Used by
 * asan_report() to stamp crash_sig so the host can group crashes at the same
 * parser site to the same signature. Reads the raw (pre-classify) counters
 * because ASan fires mid-execution, before coverage_evaluate clears the map. */
u32  __coqui_trace_sig(u8 *map, u64 cov_map_size);

/* -- SanitizerCoverage callbacks (coqui_sancov.c). Invoked by clang-emitted
 *    instrumentation when the target is compiled with
 *    -fsanitize-coverage=trace-pc-guard. --
 */
void __sanitizer_cov_trace_pc_guard(unsigned int *guard);
void __sanitizer_cov_trace_pc_guard_init(unsigned int *start,
                                          unsigned int *stop);

/* Heap allocator (coqui_memory.c) */
void *__coqui_malloc(unsigned long size);
void  __coqui_free(void *ptr);
void *__coqui_calloc(unsigned long n, unsigned long size);
void *__coqui_realloc(void *ptr, unsigned long size);

/* ASan heap instrumentation (coqui_asan.c) */
void *__coqui_asan_malloc(unsigned long size);
void  __coqui_asan_free(void *ptr);
void  __coqui_asan_check_load_1(void *ptr);
void  __coqui_asan_check_load_2(void *ptr);
void  __coqui_asan_check_load_4(void *ptr);
void  __coqui_asan_check_load_8(void *ptr);
void  __coqui_asan_check_store_1(void *ptr);
void  __coqui_asan_check_store_2(void *ptr);
void  __coqui_asan_check_store_4(void *ptr);
void  __coqui_asan_check_store_8(void *ptr);

/* Libc replacements (coqui_libc.c) */
unsigned long __coqui_strlen(const char *s);
int  __coqui_strcmp(const char *a, const char *b);
int  __coqui_strncmp(const char *a, const char *b, unsigned long n);
int  __coqui_memcmp(const void *a, const void *b, unsigned long n);
char *__coqui_strchr(const char *s, int c);
double __coqui_strtod(const char *nptr, char **endptr);

/* -- Kernel entry (generated by FuzzEntry transform) -- */

/* Renamed user entry (was LLVMFuzzerTestOneInput). Called by kernel per-thread. */
int __coqui_fuzz_execute(const unsigned char *data, unsigned long size);

/* Device-global virgin map base pointer — host cuMemAllocs the bitmap and
 * binds it via cuModuleGetGlobal("__coqui_virgin_map_ptr"). The size is
 * determined at module load from @__coqui_num_edges (rounded up to 4). */
extern u8 *__coqui_virgin_map_ptr;

/* Device-global cov pool base pointer — host cuMemAllocs a batch-size *
 * cov_map_size counter pool and binds it via cuModuleGetGlobal(). The
 * MemoryLayout pass computes each thread's cov_base as base + tid * size. */
extern u8 *__coqui_cov_map_pool_ptr;

/* SanCov edge count (emitted as i64 constant by SancovCount pass). */
extern unsigned long __coqui_num_edges;

#endif /* _COQUI_RUNTIME_H */
